version: '3.9'

services:
  frontend:
    image: quetwo/cf-docker-skel:latest
    build:
      context: frontend/
      dockerfile: Dockerfile.prod
    depends_on:
      - db
    ports:
      - "80:8888"

  db:
    image: mysql:5.7
    env_file:
      - ./db/secrets.txt
    volumes:
      - vol_db:/var/lib/mysql
      - ./db/dump:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

# Mounts
volumes:
  vol_db:
