services:

  # Front-End configuration for the running application
  # Exposed for all HTTP and HTTPS traffic, routed via port 8888
  # ---------------
  # Make sure to create ./frontend/secrets.txt
  frontend:
    image: quetwo/cf-docker-skel:latest
    build:
      context: frontend/
    depends_on:
      - db
    volumes:
      - ./frontend/webroot:/var/www
    env_file:
      - ./frontend/secrets.txt
      - ./db/secrets_shared.txt
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.routers.frontends.entrypoints=websecure"
      - "traefik.http.routers.frontends.tls=true"
      - "traefik.http.routers.frontends.tls.certresolver=myresolver"
      - "traefik.http.routers.frontends.tls.domains[0].main=dev.host.com"
      - "traefik.http.services.web.loadbalancer.server.port=8888"

  # MySQL/Maria Database Configuration
  # Ports 3306 Exposed for local traffic only
  # -----------------
  # Make sure to create ./db/secrets.txt and ./db/secrets_shared.txt
  db:
    image: mariadb:latest
    env_file:
      - ./db/secrets.txt
      - ./db/secrets_shared.txt
    volumes:
      - vol_db:/var/lib/mysql
      - ./db/dump:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    healthcheck:
        test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
        start_period: 10s
        interval: 10s
        timeout: 5s
        retries: 3

  # Reverse Proxy to handle HTTP/HTTPS traffic.
  # Port 8080 is exposed to show diag info.  See /proxy/config.toml for proxy config
  proxy:
    image: traefik:latest
    depends_on:
      - frontend
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - cert_db:/shared/certs/
      - ./proxy/config.toml:/etc/traefik/traefik.toml

# Mounts
volumes:
  vol_db:
  cert_db: